FROM fedora:latest

ARG USERNAME=dev
ARG UID=1000
ARG GID=$UID

RUN dnf install -y \
    git \
    gpg \
    openssh \
    sudo

RUN groupadd -g $GID $USERNAME \
    && useradd -m -u $UID -g $GID $USERNAME \
    && usermod -aG wheel $USERNAME \
    && echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

COPY lifecycle /

COPY extra-packages /
RUN dnf install -y $(cat /extra-packages)

COPY extra-setup /
RUN chmod o+x /extra-setup
RUN . /extra-setup

USER $USERNAME

COPY user-setup /
RUN sudo chown $USERNAME:$USERNAME /user-setup
RUN chmod o+x /user-setup 
RUN . /user-setup